"""add product size and color

Revision ID: 07e9f889dcf9
Revises: 06f969489b2e
Create Date: 2026-09-06 15:28:07.673004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07e9f889dcf9'
down_revision: Union[str, Sequence[str], None] = '06f969489b2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('size', sa.String(length=100), nullable=True))
    op.add_column('products', sa.Column('color', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'color')
    op.drop_column('products', 'size')
    # ### end Alembic commands ###
