import { useEffect, useState } from 'react'
import { createKnowledge, createProduct, deleteKnowledge, deleteProduct, getConversation, getKnowledge, getProducts, getSellerOrder, getStores, updateKnowledge, updateProduct } from './api'

const emptyProduct = { name: '', description: '', price: '', stock: 0, size: '', color: '', is_active: true }
const emptyKnowledge = { title: '', content: '', is_active: true }

function Panel({ title, children }) { return <section className="card" style={{ marginBottom: 18 }}><div className="section-head"><h2>{title}</h2></div>{children}</section> }
function Field({ label, value, onChange, type = 'text' }) { const id = `seller-${label.toLowerCase().replace(/\s+/g, '-')}`; return <div className="field"><label htmlFor={id}>{label}</label><input id={id} aria-label={label} type={type} value={value} onChange={e => onChange(e.target.value)} required={label === 'Name' || label === 'Title'} /></div> }

export function SellerProducts({ t }) {
  const token = localStorage.getItem('nava_seller_token'); const [store, setStore] = useState(null); const [items, setItems] = useState([]); const [form, setForm] = useState(emptyProduct); const [editing, setEditing] = useState(null); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const [loading, setLoading] = useState(true)
  const load = async () => { setLoading(true); try { const stores = await getStores(token); const current = stores[0]; setStore(current); if (current) setItems(await getProducts(current.id, token)) } catch (e) { setError(e.message) } finally { setLoading(false) } }
  useEffect(() => { load() }, [])
  const submit = async e => { e.preventDefault(); setBusy(true); setError(''); try { const payload = { ...form, price: Number(form.price), stock: Number(form.stock) }; if (editing) await updateProduct(editing, payload, token); else await createProduct({ ...payload, store_id: store.id }, token); setForm(emptyProduct); setEditing(null); await load() } catch (e) { setError(e.message) } finally { setBusy(false) } }
  const remove = async id => { try { await deleteProduct(id, token); await load() } catch (e) { setError(e.message) } }
  const toggle = async item => { try { await updateProduct(item.id, { is_active: !item.is_active }, token); await load() } catch (e) { setError(e.message) } }
  return <main className="seller-main"><span className="eyebrow">Catalog management</span><h1>{t.locale === 'fa' ? 'محصولات' : 'Products'}</h1><Panel title={editing ? (t.locale === 'fa' ? 'ویرایش محصول' : 'Edit product') : (t.locale === 'fa' ? 'افزودن محصول' : 'Add product')}><form className="form-grid" onSubmit={submit}><Field label="Name" value={form.name} onChange={v => setForm({ ...form, name: v })}/><Field label="Price" type="number" value={form.price} onChange={v => setForm({ ...form, price: v })}/><Field label="Stock" type="number" value={form.stock} onChange={v => setForm({ ...form, stock: v })}/><Field label="Size" value={form.size} onChange={v => setForm({ ...form, size: v })}/><Field label="Color" value={form.color} onChange={v => setForm({ ...form, color: v })}/><div className="field full"><label>Description</label><textarea value={form.description} onChange={e => setForm({ ...form, description: e.target.value })}/></div><div className="field full"><label>Attributes (JSON)</label><textarea value={form.attributes ? JSON.stringify(form.attributes, null, 2) : ''} onChange={e => { try { setForm({ ...form, attributes: e.target.value ? JSON.parse(e.target.value) : {} }) } catch { setForm({ ...form, attributes: e.target.value }) } }} placeholder='{"material":"cotton"}' /></div><div className="actions"><button className="btn btn-primary" disabled={busy || !store}>{busy ? 'Saving...' : editing ? 'Save changes' : 'Create product'}</button>{editing&&<button type="button" className="btn btn-ghost" onClick={() => { setEditing(null); setForm(emptyProduct) }}>Cancel</button>}</div></form></Panel>{error&&<p role="alert" style={{ color: 'var(--danger)' }}>{error}</p>}<Panel title={t.locale === 'fa' ? 'کاتالوگ' : 'Catalog'}>{loading ? <div className="state">Loading...</div> : !items.length ? <div className="state">{t.locale === 'fa' ? 'محصولی ثبت نشده است.' : 'No products yet.'}</div> : <div className="table-wrap"><table><thead><tr><th>Name</th><th>Price</th><th>Stock</th><th>Status</th><th /></tr></thead><tbody>{items.map(item => <tr key={item.id}><td>{item.name}<br/><small>{item.color} · {item.size}</small></td><td>{item.price}</td><td>{item.stock}</td><td><button className={`badge ${item.is_active ? '' : 'out'}`} onClick={() => toggle(item)}>{item.is_active ? 'Active' : 'Inactive'}</button></td><td><button className="btn btn-ghost" onClick={() => { setEditing(item.id); setForm({ ...item, price: String(item.price), attributes: item.attributes || {} }) }}>Edit</button> <button className="btn btn-ghost" onClick={() => remove(item.id)}>Delete</button></td></tr>)}</tbody></table></div>}</Panel></main>
}

export function SellerKnowledge({ t }) {
  const token = localStorage.getItem('nava_seller_token'); const [store, setStore] = useState(null); const [items, setItems] = useState([]); const [form, setForm] = useState(emptyKnowledge); const [editing, setEditing] = useState(null); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const [loading, setLoading] = useState(true)
  const load = async () => { setLoading(true); try { const stores = await getStores(token); const current = stores[0]; setStore(current); if (current) setItems(await getKnowledge(current.id, token)) } catch (e) { setError(e.message) } finally { setLoading(false) } }
  useEffect(() => { load() }, [])
  const submit = async e => { e.preventDefault(); setBusy(true); try { if (editing) await updateKnowledge(store.id, editing, form, token); else await createKnowledge(store.id, form, token); setForm(emptyKnowledge); setEditing(null); await load() } catch (e) { setError(e.message) } finally { setBusy(false) } }
  const remove = async id => { try { await deleteKnowledge(store.id, id, token); await load() } catch (e) { setError(e.message) } }
  return <main className="seller-main"><span className="eyebrow">Store intelligence</span><h1>{t.locale === 'fa' ? 'پایگاه دانش' : 'Knowledge Base'}</h1><Panel title={editing ? 'Edit entry' : 'Add entry'}><form className="field" onSubmit={submit}><Field label="Title" value={form.title} onChange={v => setForm({ ...form, title: v })}/><label>Content</label><textarea required value={form.content} onChange={e => setForm({ ...form, content: e.target.value })}/><button className="btn btn-primary" disabled={busy || !store}>{busy ? 'Saving...' : editing ? 'Save changes' : 'Create entry'}</button></form></Panel>{error&&<p role="alert" style={{ color: 'var(--danger)' }}>{error}</p>}<Panel title="Entries">{loading ? <div className="state">Loading...</div> : !items.length ? <div className="state">No knowledge entries yet.</div> : <div className="grid">{items.map(item => <article className="card" key={item.id}><h3>{item.title}</h3><p className="muted">{item.content}</p><button className="btn btn-ghost" onClick={() => { setEditing(item.id); setForm({ title: item.title, content: item.content, is_active: item.is_active }) }}>Edit</button> <button className="btn btn-ghost" onClick={() => remove(item.id)}>Delete</button></article>)}</div>}</Panel></main>
}

export function SellerOrderDetail() {
  const id = location.pathname.split('/').pop(); const token = localStorage.getItem('nava_seller_token'); const [order, setOrder] = useState(null); const [error, setError] = useState('')
  useEffect(() => { getSellerOrder(id, token).then(setOrder).catch(e => setError(e.message)) }, [id])
  if (error) return <main className="seller-main"><p style={{ color: 'var(--danger)' }}>{error}</p></main>
  if (!order) return <main className="seller-main"><div className="state">Loading...</div></main>
  return <main className="seller-main"><span className="eyebrow">Order detail</span><h1>Order #{order.id}</h1><div className="card"><p><strong>Customer:</strong> {order.customer_name}</p><p><strong>Phone:</strong> {order.customer_phone}</p><p><strong>Address:</strong> {order.customer_address}</p><p><strong>Total:</strong> {order.total_amount}</p><p><span className="badge">{order.status}</span></p>{order.items.map(item => <div className="cart-row" key={item.id}>{item.product_name} × {item.quantity} <strong>{item.line_total}</strong></div>)}</div></main>
}

export function SellerConversationDetail() {
  const id = location.pathname.split('/').pop(); const token = localStorage.getItem('nava_seller_token'); const [conversation, setConversation] = useState(null); const [error, setError] = useState('')
  useEffect(() => { getConversation(id, token).then(setConversation).catch(e => setError(e.message)) }, [id])
  if (error) return <main className="seller-main"><p style={{ color: 'var(--danger)' }}>{error}</p></main>
  if (!conversation) return <main className="seller-main"><div className="state">Loading...</div></main>
  return <main className="seller-main"><span className="eyebrow">Conversation detail</span><h1>Conversation #{conversation.id}</h1><div className="card"><p className="muted">State: {conversation.checkout_state} {conversation.last_order_id && `· Order #${conversation.last_order_id}`}</p>{conversation.messages.map(message => <div className="bubble assistant" style={{ margin: '10px 0' }} key={message.id}><strong>{message.role}:</strong> {message.content}</div>)}</div></main>
}
